# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

export PS1="\u@local \W $ "

PATH=$PATH:~/bin
PATH=$PATH:~/softwares/mysql-5.6.24-osx10.8-x86_64/bin
PATH=$PATH:~/softwares/mongodb/bin
PATH=~/softwares/vim8/bin:$PATH

export PATH
